spring:
  application:
    name: hokan-cloud-bot-eureka-engine
  profiles:
    active=dev:server:
  port: 8003

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true